version: "3.7"

services:
  portainer:
    image: portainer/portainer-ce
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    ports:
      - 127.0.0.1:9000:9000
    networks:
      backend:
    labels:
      - traefik.enable=true
      # Frontends
      - traefik.http.routers.portainer-frontend.rule=Host(`portainer.${ROOT_DOMAIN}`)
      - traefik.http.routers.portainer-frontend.entrypoints=websecure
      - traefik.http.services.portainer-frontend.loadbalancer.server.port=9000
      - traefik.http.routers.portainer-frontend.service=portainer-frontend
      - traefik.http.routers.portainer-frontend.middlewares=authelia@docker
      # Edge
      - traefik.http.routers.portainer-edge.rule=Host(`portainer-edge.${ROOT_DOMAIN}`)
      - traefik.http.routers.portainer-edge.entrypoints=websecure
      - traefik.http.services.portainer-edge.loadbalancer.server.port=8000
      - traefik.http.routers.portainer-edge.service=portainer-edge

networks:
  backend:
    external: true
