version: "3.7"

services:
  authelia:
    image: authelia/authelia
    environment:
      - AUTHELIA_LOG_LEVEL=${AUTHELIA_LOG_LEVEL}
      - AUTHELIA_JWT_SECRET=${AUTHELIA_JWT_SECRET}
      - AUTHELIA_TOTP_ISSUER=login.${ROOT_DOMAIN}
      - AUTHELIA_SESSION_DOMAIN=${ROOT_DOMAIN}
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}

      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_IMPLEMENTATION=${LDAP_IMPLEMENTATION}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_URL=${LDAP_URL}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN=${LDAP_BASE_DN}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDITIONAL_USERS_DN=${LDAP_ADDITIONAL_USERS_DN}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USERNAME_ATTRIBUTE=${LDAP_USERNAME_ATTRIBUTE}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USERS_FILTER=${LDAP_USERS_FILTER}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDITIONAL_GROUPS_DN=${LDAP_ADDITIONAL_GROUPS_DN}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_GROUP_NAME_ATTRIBUTE=${LDAP_GROUP_NAME_ATTRIBUTE}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_GROUPS_FILTER=${LDAP_GROUPS_FILTER}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_MAIL_ATTRIBUTE=${LDAP_MAIL_ATTRIBUTE}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER=${LDAP_USER}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD=${LDAP_PASSWORD}
    volumes:
      - ./config:/config
      - ./data:/data
    networks:
      backend: null
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`login.${ROOT_DOMAIN}`)
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.${ROOT_DOMAIN}/
      - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email
    expose:
      - 9091
    restart: unless-stopped

  whoami:
    image: traefik/whoami
    networks:
      backend: null
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.${ROOT_DOMAIN}`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.middlewares=authelia@docker

networks:
  backend:
    external: true
