version: '3.7'

services:
  coredns:
    image: coredns/coredns
    restart: unless-stopped
    volumes:
      - ./coredns/Corefile:/Corefile:ro
    networks:
      backend:
        ipv4_address: 172.28.241.10

  pihole:
    image: jacklul/pihole
    restart: unless-stopped
    environment:
      CORS_HOSTS: pihole.${ROOT_DOMAIN}
      TZ: Europe/London
      DNS1: 172.28.241.10
      DNS2: 172.28.241.10
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      BLOCKING_ENABLED: "true"
    ports:
      - '${DNS_INTERFACE_IPV4}:53:53/tcp'
      - '${DNS_INTERFACE_IPV4}:53:53/udp'
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
      - ./etc-pihole-updatelists/:/etc/pihole-updatelists/
    networks:
      backend:
        ipv4_address: 172.28.241.11
    depends_on:
      - coredns
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`pihole.${ROOT_DOMAIN}`)
      - traefik.http.routers.pihole.entrypoints=websecure
      - traefik.http.routers.pihole.service=pihole
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - traefik.http.routers.pihole.middlewares=authelia@docker

networks:
  backend:
    external: true