http:
  routers:
    omv:
      rule: 'Host(`omv.{{env "ROOT_DOMAIN"}}`)'
      service: omv
      entrypoints:
        - websecure
      middlewares:
        - default-headers
        - authelia@docker

  services:
    omv:
      loadBalancer:
        servers:
          - url: 'http://{{env "PI_HOST"}}:80'
        passHostHeader: true

  middlewares:
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
    crowdsec-bouncer:
      forwardauth:
        address: http://bouncer-traefik:8080/api/v1/forwardAuth
        trustForwardHeader: true

tls:
  {{ if eq (env "REPLACE_DEFAULT_CERTIFICATE") "true" }}
  stores:
    default:
      defaultCertificate:
        certFile: {{env "DEFAULT_CERTIFICATE_CERT_FILE"}}
        keyFile: {{env "DEFAULT_CERTIFICATE_KEY_FILE"}}
  {{ end }}