version: '3.7'

services:
  vpn:
    image: kylemanna/openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - 1194:1194/udp
      - 80:80
      - 443:443
      - 445:445
    restart: unless-stopped
    volumes:
      - ./openvpn-data/conf:/etc/openvpn
    devices:
      - /dev/net/tun
    networks:
      backend:
    extra_hosts:
      - host.docker.internal:host-gateway

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    network_mode: service:vpn
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - vpn

  squid:
    image: babim/squid
    restart: unless-stopped
    network_mode: host
    environment:
      - AUTH=true
      - USERNAME=${SQUID_USERNAME}
      - PASSWORD=${SQUID_PASSWORD}
    ports:
      - 3128:3128

  haproxy:
    image: haproxy
    restart: unless-stopped
    network_mode: service:vpn
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - vpn

  coredns:
    image: coredns/coredns
    restart: unless-stopped
    volumes:
      - ./Corefile:/Corefile:ro
    networks:
      backend:
        ipv4_address: 172.28.241.8

  pihole:
    image: pihole/pihole
    restart: unless-stopped
    environment:
      CORS_HOSTS: ${PIHOLE_CORS_HOSTS}
      TZ: Europe/London
      DNS1: 172.28.241.8
      DNS2: 172.28.241.8
      WEBPASSWORD: ${PIHOLE_PASSWORD}
    ports:
      - ${DNS_INTERFACE_IPV4}:53:53/tcp
      - ${DNS_INTERFACE_IPV4}:53:53/udp
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    networks:
      backend:
        ipv4_address: 172.28.241.9
    depends_on:
      - coredns

  dnsrobocert:
    image: adferrand/dnsrobocert
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./dnsrobocert:/etc/dnsrobocert

networks:
  backend:
    name: backend
    ipam:
      config:
        - subnet: 172.28.241.0/24