version: "3.7"

services:
  wireguard:
    image: linuxserver/wireguard
    restart: unless-stopped
    volumes:
      - "./wireguard/wg0.conf:/config/wg0.conf"
      - "/lib/modules:/lib/modules:ro"
    environment:
      - PUID=1000
      - PGID=1000
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

  haproxy:
    image: haproxy
    restart: unless-stopped
    network_mode: service:wireguard
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - wireguard

  rtmp-recorder:
    image: nginx-rtmp
    restart: unless-stopped
    ports:
      - 1935:1935
    volumes:
      - ./rtmp-recorder/nginx.conf:/etc/nginx/nginx.conf.template
      - ${RTMP_RECORDS_FOLDER}:/opt/data/records/

  portainer-edge-agent:
    image: portainer/agent:2.9.2
    restart: unless-stopped
    volumes:
      - /:/host
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ./portainer_data:/data
    environment:
      - EDGE_INSECURE_POLL=0
      - CAP_HOST_MANAGEMENT=1
      - EDGE_KEY=${PORTAINER_EDGE_KEY}
      - EDGE_ID=${PORTAINER_EDGE_ID}
