version: '3.7'

services:
  nexus:
    image: sonatype/nexus3
    restart: unless-stopped
    volumes:
      - ./nexus-data:/nexus-data
    networks:
      backend: null
    labels:
      - traefik.enable=true
      - traefik.http.routers.artifactory.rule=Host(`artifactory.${ROOT_DOMAIN}`)
      - traefik.http.routers.artifactory.entrypoints=websecure
      - traefik.http.routers.artifactory.service=artifactory
      - traefik.http.services.artifactory.loadbalancer.server.port=8081
      # Docker Connector
      - traefik.http.routers.docker-connector.rule=Host(`docker.${ROOT_DOMAIN}`)
      - traefik.http.routers.docker-connector.entrypoints=websecure
      - traefik.http.services.docker-connector.loadbalancer.server.port=5000
      - traefik.http.routers.docker-connector.service=docker-connector
      # Private Docker Connector
      - traefik.http.routers.private-docker-connector.rule=Host(`docker-private.${ROOT_DOMAIN}`)
      - traefik.http.routers.private-docker-connector.entrypoints=websecure
      - traefik.http.services.private-docker-connector.loadbalancer.server.port=5001
      - traefik.http.routers.private-docker-connector.service=private-docker-connector

networks:
  backend:
    external: true
