---
theme: dark

# default_redirection_url: https://home.example.com/

server:
  host: 0.0.0.0
  port: 9091

  path: ""

  read_buffer_size: 4096
  write_buffer_size: 4096

  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false

totp:
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1


ntp:
  address: "time.cloudflare.com:123"
  version: 4
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false

authentication_backend:
  disable_reset_password: false
  refresh_interval: 30s

session:
  name: authelia_session
  same_site: lax
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  local:
    path: /data/db.sqlite3

notifier:
  disable_startup_check: false

  filesystem:
    filename: /data/notification.txt

access_control:
  default_policy: deny

  rules:
    - domain: "*."
      subject:
        - group:admins
      policy: two_factor
...
